services:
  - type: web
    name: enabling2-app
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    plan: free
    healthCheckPath: /
    envVars:
      - key: DB_DRIVER
        value: com.mysql.jdbc.Driver
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
